### ISSUE TITLE
enhancement: batch file are sourced(not exec) operation in lua script

### ISSUE THREAD

**Issue by tsuyoshicho** [nyaosorg/nyagos#421]
すでに実行可能だった場合はすみません。

現在のLua script内でバッチファイルを実行したとき、サブプロセス的にしか実行できずsourceするような動作が実現できません。

Case 1
手動動作だとバッチファイルの内容が現在のシェルに反映されます。

```console
$ .venv\Scripts\activate.bat 
(.venv) $ (イメージです)
````

Case 2
これをalias関数で、たとえば次のようにしたとき、venvをactivateすることができません。

```lua
if nyagos.which("python") then
  -- venv activate
  nyagos.alias.activate = function(args)
    local fsObj = nyagos.create_object("Scripting.FileSystemObject")
    local venv = ".venv"
    if args[1] then
      -- venv use args
      venv = args[1]
    end
    -- check venv
    local path = nyagos.pathjoin(nyagos.getwd(), venv)
    if fsObj:FolderExists(path) then
      nyagos.write("Folder exists:" .. path .. "\n")
      nyagos.write("Activate...")
      local batfile = nyagos.pathjoin(path, "Scripts", "activate.bat")
      nyagos.rawexec(batfile)
      nyagos.write("done\n")
    else
      nyagos.write("Folder do not exists:" .. path .. "\n")
    end
    fsObj:_release()  -- script object need to release
  end
end
```

```console
$ .ls -al
...
drwx---   0 Dec 11 2020     .venv/
$ activate 
$ (アクティブにならない)
````

いくつかのツールはbatchファイルを提供しているので、それの利用は普通に行うと思いますが、これをaliasなどLua scriptからも制御したい、というのが要点になります。

**Comment by hymkor** [comment]
たいへん、申し訳ありません。このあたりのこと、まったくドキュメントに書いてませんでした（[関数リファレンス](https://github.com/nyaosorg/nyagos/blob/master/docs/07-LuaFunctions_ja.md#errorlevelerrormessage--nyagosexec%E3%82%B7%E3%82%A7%E3%83%AB%E3%82%B3%E3%83%9E%E3%83%B3%E3%83%89) に項目はあるが、どういう違いがあるかなど、読み取ることが不可能だった）

試しに `nyagos.rawexec` となっているところを `nyagos.exec` と「raw」を外して、試してみていただけますでしょうか。これらの違いですが

- `nyagos.exec` … nyagos自身のシェル解釈機能でプロセスを実行する。すべての内蔵コマンドも利用可能
- `nyagos.rawexec` …  Go言語の標準関数（exec.Command）を使ってプロセスを実行する。nyagos の内蔵コマンドが使えないかわりに、余計な処理が入らないから軽い。関数の引数が UTF8 として解釈される
- `os.execute` … Luaの標準関数でプロセスを実行する。こちらは lua53.dll を使っていた時は引数が ANSI(ShiftJIS) で解釈されるという違いがあったが、GopherLua になってから `nyagos.rawexec` とほぼ同じになってしまった（結果、nyagos.rawexec の存在意義がなくなってしまった）

となります。簡単に実験すると、こんな感じになります。

![image](https://user-images.githubusercontent.com/3752189/179353313-74256836-594a-4eed-b39d-d46e8bc073ac.png)

rawexec だと環境変数 HOGE の更新がバッチファイル内だけで終わってしまいますが、exec だとシェル側にも取り込まれているのが分かると思います。

このあたりをソースから確認する場合でも、nyagos.rawexec は "functions/builtinfunc_windows.go" と普通の場所にあるのに、nyagos.exec は "mains/functions.go" という変な場所にあるので、存在すら気がつけないことが多いと思います（自分も探してしまいました…どうも、サブパッケージの呼び出しの親子関係の都合、ここにおいてあるみたいです）

ご確認いただけますでしょうか（ドキュメントの方はいずれ更新しておきたいと思います）

よろしくお願い致します。

**Comment by tsuyoshicho** [comment]
なるほど、説明ありがとうございます、試してみます。

(exec は シェル内蔵機能を呼ぶ専用と思っていました)

---

@hymkor 
上手く動きました、ありがとうございます。

なお、これにともない別件に近いですが経過として報告します。

この方法で実行可能になったところで、deactivate処理も試したところ

本家deactivate

```dosbatch
@echo off

set VIRTUAL_ENV=

REM Don't use () to avoid problems with them in %PATH%
if not defined _OLD_VIRTUAL_PROMPT goto ENDIFVPROMPT
    set "PROMPT=%_OLD_VIRTUAL_PROMPT%"
    set _OLD_VIRTUAL_PROMPT=
:ENDIFVPROMPT

if not defined _OLD_VIRTUAL_PYTHONHOME goto ENDIFVHOME
    set "PYTHONHOME=%_OLD_VIRTUAL_PYTHONHOME%"
    set _OLD_VIRTUAL_PYTHONHOME=
:ENDIFVHOME

if not defined _OLD_VIRTUAL_PATH goto ENDIFVPATH
    set "PATH=%_OLD_VIRTUAL_PATH%"
    set _OLD_VIRTUAL_PATH=
:ENDIFVPATH
```

alias実装
```lua
-- python
-- use nyagos.exec for shell builtin execution
if nyagos.which("python") then
  -- venv activate
  nyagos.alias.activate = function(args)
    local fsObj = nyagos.create_object("Scripting.FileSystemObject")
    local venv = ".venv"
    if args[1] then
      -- venv use args
      venv = args[1]
    end
    -- check venv
    local path = nyagos.pathjoin(nyagos.getwd(), venv)
    if fsObj:FolderExists(path) then
      nyagos.write("Folder exists:" .. path .. "\n")
      nyagos.write("Activate...")
      local batfile = nyagos.pathjoin(path, "Scripts", "activate.bat")
      nyagos.exec(batfile)
      nyagos.write("done\n")
    else
      nyagos.write("Folder do not exists:" .. path .. "\n")
    end
    fsObj:_release()  -- script object need to release
  end
  -- venv deactivate
  nyagos.alias.deactivate = function(args)
    -- VIRTUAL_ENV check
    local deactivate = "deactivate.bat"
    if nyagos.env["VIRTUAL_ENV"] and nyagos.which(deactivate) then
      -- execute deactivate.bat
      nyagos.write("Deactivate...")
      nyagos.exec(deactivate)
      -- nyagos.env["VIRTUAL_ENV"] = nil
      nyagos.write("done\n")
    end
  end
end
```

aliasでは `set VIRTUAL_ENV=` 環境変数 `VIRTUAL_ENV` の削除処理が行えておらず、コメントで入れている削除処理が必要でした。

現状制限かもしれませんが、連絡まで。

**Comment by hymkor** [comment]
ご報告ありがとうございます。

> aliasでは set VIRTUAL_ENV= による環境変数 VIRTUAL_ENV の削除処理が行えておらず、コメントで入れている削除処理が必要でした。
>
> 現状制限かもしれませんが、連絡まで。

はい。対応できなくもないが、この仕組を組んだ当時はニーズが感じられない割に危険に感じたため、そこまでやってないという感じでした。

バッチファイルを実行する時は、`cmd /c "call バッチファイル名 引数 & call set ERRORLEVEL_=%^ERRORLEVEL% & (cd & set) > テンポラリファイル"` とやって、修正された環境変数をテンポラリファイルから拾っていますが、消されたものはテンポラリファイルに出力されないので、漏れてしまったのだと思います。

でも、現在ある環境変数の中から、テンポラリファイルに出ていない環境変数を消す処理を入れればいけそうですね
（まぁ、プロセス内の環境変数が消える程度、そう構えて危険でもないか…）

**Comment by tsuyoshicho** [comment]
変更ありがとうございます。

主題はすでに対応できていること、追加報告も対応は済んだため、誤解を避けるためにもCloseします。
(次リリースされたら削除処理を外すのはありますが、自分ごとなので)
