### ISSUE TITLE
"" in command line

### ISSUE THREAD

**Issue by juggler999** [nyaosorg/nyagos#426]
いつもありがとうございます．
少し前のバージョン以降，コマンドライン文字列における""が無視されるようになっているようですが，これを空文字列として扱う仕様に戻していただけないでしょうか?
例えば，オプション-oのオプション引数を期待する以下のコマンドラインで空文字列を指定したと解釈する仕様に戻してほしいと思っています(以前はそのように解釈され動作していたと思います)：
    some_script -i ARGI-o ""
あるいはなにか実装上の理由があるのでしょうか?

**Comment by hymkor** [comment]
> 少し前のバージョン以降，コマンドライン文字列における""が無視されるようになっているようですが，これを空文字列として扱う仕様に戻していただけないでしょうか?

すみません。どのコマンドラインでのパラメータで `""` が空文字にならないというお話なのか…がよく分かりません。

1. ショートカットや、他のコマンドから nyagos.exe 自体を起動する際に与えるパラメータ
2. nyagos 内で、lua関数をコマンドで起動する時のパラメータ
3. nyagos 内で、内部コマンドを起動する時のパラメータ（set とか？）
4. nyagos 内で、外部コマンドを起動する時のパラメータ

比較的最近、仕様が変わったものといえば 1. ですが、-c , -k などコマンドを文字列として与えるオプションはあるものの、空文字列を与えて意味があるものはなかったように思うので、ちょっと本件のことかどうか、判断しかねています。

できましたら「例えば…」ではなく、実際にうまく機能しない実例を出していただけると、たすかります。
よろしくお願いいたします。
@juggler999

**Comment by juggler999** [comment]
4.に該当します．下の実例で
"-i", "ARGI", "-o",""
のように解釈されてほしいという意味です．
実行環境は
Windows10+Windows Terminal 1.15.2712_0+Nyagos 4.4.12_0-windows-386
で，perlは
perl 5, version 32, subversion 1 (v5.32.1) built for MSWin32-x86-multi-thread-64int
です．
なおCmderターミナル，perl 5.24.3でも同様です．

% cat argv.pl
print join( ', ', map qq("$_"), @ARGV ), "\n";

% perl argv.pl -i ARGI -o ""
"-i", "ARGI", "-o"

**Comment by hymkor** [comment]
手元で確認したところ、nyagos 本体の外部コマンド起動そのものではなく、インタプリタ名を省略した時のコマンドラインフィルターを通した時だけ現象が発生するように見えますが、同様の結果でしょうか？

![image](https://user-images.githubusercontent.com/3752189/193409843-e791ca04-7179-4929-929a-c197839f5282.png)

@juggler999

**Comment by juggler999** [comment]
$ perl argv.pl -i ARGI -o ""
も
$ ./argv.pl -i ARGI -o ""
も同じ結果で，""は返されません．
ただ気になりますので，もう少し現在の環境(Nyagosの設定，環境変数，ftype, assocの設定など)を調べてみて報告します．

**Comment by hymkor** [comment]
`nyagos --norc` で起動した nyagos 環境でも、試してみていただけないでしょうか？ @juggler999 
（Lua スクリプトを全くロードしないモードです）

**Comment by juggler999** [comment]
いまのNyagos環境から以下を実行しました．次のように""が返されました．

% /utils/nyagos/nyagos.exe --norc
% perl ./argv.pl -i ARGI -o ""
"-i", "ARGI", "-o", ""

**Comment by hymkor** [comment]
コマンドラインフィルター （nyagos.argsfilter）でを通すと、0文字の引数が消える不具合を修正しました。

- 386版バイナリスナップショット：[nyagos-i386-1.0.1756.zip](https://ci.appveyor.com/api/buildjobs/068141ee99qtje58/artifacts/bin%2Fnyagos-i386-1.0.1756.zip)
- amd65版バイナリスナップショット：[nyagos-amd64-1.0.1756.zip](https://ci.appveyor.com/api/buildjobs/5ucf5q4pj9qxneep/artifacts/bin%2Fnyagos-amd64-1.0.1756.zip)

ただ、これは通常インタプリタ名を省略した時に、nyagos.d\suffix.lua を元にインタプリタ名が挿入された時だけ機能するはずなので、これとは別に何かが誤動作していると思われます。

コマンドラインで `suffix` を実行した時、どんな感じでしょうか

```
$ suffix
awk=gawk -f
js=cscript //nologo
lua=nyagos.exe --norc --lua-file
pl=perl
ps1=powershell -ExecutionPolicy RemoteSigned -file
rb=ruby
vbs=cscript //nologo
wsf=cscript //nologo
py=python
```

**Comment by juggler999** [comment]
suffix は上とまったく同じです．

[nyagos-i386-1.0.1756.zip]で試した結果は以下で，両方ともうまくいっています．

% perl ./argv.pl -i ARGI -o ""
"-i", "ARGI", "-o", ""

% ./argv.pl -i ARGI -o ""
"-i", "ARGI", "-o", ""

**Comment by hymkor** [comment]
ありがとうございます。一応は直ったようですね。次のリリースでは上の修正がそのまま入る予定です。

とはいえ、やはりコマンドラインフィルターが本来動かない状況で、なぜか変な形で動いてしまっている原因が不明のままなので、また別の形で誤動作が出るかもしれません。また何かしら症状出ましたら、教えていただけますでしょうか

（ たぶんコマンドラインフィルターが機能すると「一旦、二重引用符を外して、また必要に応じてつける」というような処理が動くので、二重引用符の有無でパラメータの解釈を変えるというようなコマンド（ Windows 標準の find コマンドとか for ）などが期待どおりに動作しないと思います ）

**Comment by juggler999** [comment]
ありがとうございます．
今朝の先の報告の後，もう少し試してみました．その結果，[nyagos-i386-1.0.1756.zip]においても
次の場合に "" の扱いがうまくいかないようです．
(1) _nyagos に set -o glob の行を置く
(2) .nyagos に nyagos.option.glob = true の行を置く
(3) nyagos.exe --glob
もしやワイルドカード展開との関連でなにかが起こっているのでしょうか?

**Comment by hymkor** [comment]
どうやら、こちらの方が本命だったようです。ワイルドカード展開が外部コマンドに対しても有効な時に、こちらも別の引数の置き換え処理が走るのですが、二重引用符で囲む/囲まないの判定が argsfilter の時と同様の不具合がありました。

- （誤）１引数の中に `&|<>"` やスペース・タブが含まれていたら、その引数は二重引用符で囲む必要あり
- （正）１引数の中に `&|<>"` やスペース・タブが含まれているか、**あるいは引数の長さがゼロであれば**、その引数は二重引用符で囲む必要あり

とりいそぎ対応しました。

- 386用バイナリ：https://ci.appveyor.com/api/buildjobs/5agbl27llkaevgaj/artifacts/bin%2Fnyagos-i386-1.0.1758.zip
- amd64用バイナリ：https://ci.appveyor.com/api/buildjobs/qgpud83naddc1nx0/artifacts/bin%2Fnyagos-amd64-1.0.1758.zip

どうも、カスタマイズなしの素の状態であれば出来るだけ入力されたままの状態を維持するので基本問題はないが、何らかのオプション機能で引数単位での変換処理が発生すると `""` が飛んでしまいがちのようです。これは対応漏れというよりは、そもそもそういうケースそのものを想定していなかったというのが主な理由になると思います。

他にもあるかもしれないので、見つかり次第、それぞれ個別に対応ですね

**Comment by juggler999** [comment]
"" の件も glob の件も期待どおりに動作していることを確認しました．
これでまた Happy Nyagos Life を満喫できます．
ありがとうございました．またきちんをご対応いただいたこと，感謝しています．

**Comment by hymkor** [comment]
修正版バイナリもリリースしていますので、クローズします。

- [Release 4.4.13_1 · nyaosorg/nyagos](https://github.com/nyaosorg/nyagos/releases/tag/4.4.13_1)
