### ISSUE TITLE
シングルクォートで囲まれた文字列中にダブルクォートで囲まれた文字列があると"(1)"のように置換される

### ISSUE THREAD

**Issue by hogewest** [nyaosorg/nyagos#427]
## 環境
* nyagos : nyagos-4.4.13_0-windows-amd64
* OS : Windows10 Pro 21H2

## 事象
シングルクォートで囲まれた文字列中にダブルクォートで囲まれた文字列がある場合に`(1)`のように置換されます。

例
```
$ echo '""'
'(1)'
$ echo 'abc"abc""d"'
'abc(1)(2)'
```

期待する結果
```
$ echo '""'
'""'
$ echo 'abc"abc""d"'
'abc"abc""d"'
```

## 事象が発生するようになったバージョン
4.1.7.0 から発生するようになっていました。
```
Nihongo Yet Another GOing Shell 4.1.6_1-amd64 Powered by go1.7 & Lua 5.3
Copyright (c) 2014-2016 HAYAMA_Kaoru and NYAOS.ORG
$echo '""'
""
```

```
Nihongo Yet Another GOing Shell 4.1.7_0-amd64 by go1.7.3 & Lua 5.3
(c) 2014-2016 NYAOS.ORG <http://www.nyaos.org>
[D:/test/nyagos-4.1.7_0-amd64]
$ echo '""'
(1)
```

**Comment by hymkor** [comment]
ご報告ありがとうございます。

どうも、原因は nyagos.d/brace.lua にあるようです。
これを削除したり、`nyagos --norc` で起動した場合は、ビープ音+(数字) に変換される現象が発生しなくなりました。

多分、置換処理が多重に行われないように作った仕組みだったと思いますが、何か誤動作しているようです。

修正しますので、少々お待ちいただけますでしょうか

**Comment by hymkor** [comment]
原因が分かりました。

brace.lua は UNIX のシェルの {} の動作＝ `A{1,2}B` → `A1B A2B` の置換を行うスクリプトなんですが、この置換を二重引用符や一重引用符に囲まれた中では動作しないように、`"～"` や `'～'` を一時的に別の文字列（`\a(通し番号)` )に置き換える処理が誤動作していました。

`'""' ` という文字列は、二重引用符と一重引用符に二回囲まれているので `\a(通し番号)` への変換が２回動くのですが、戻す処理は１回しか動かないため、元に戻し損なっていたようです。

同じ場所で２回に動くこと自体がまずいので、正規表現を調整して１回しか行われないよう修正しました（ 7a8e61c ）

```diff
diff --git a/nyagos.d/brace.lua b/nyagos.d/brace.lua
index bdcdcf42..8c23ae5c 100644
--- a/nyagos.d/brace.lua
+++ b/nyagos.d/brace.lua
@@ -18,7 +18,7 @@ nyagos.filter = function(cmdline)
         return '\a('..i..')'
     end
     cmdline = cmdline:gsub('"[^"]*"', masking)
-    cmdline = cmdline:gsub("'[^']*'", masking)
+    cmdline = cmdline:gsub("'[^'\a]*'", masking)
     repeat
         local last = true
         cmdline = cmdline:gsub("(%S*)(%b{})(%S*)", function(left,mid,right)
```

**Comment by hymkor** [comment]
上の修正では、一重引用符の中の {,,,} 変換が「動作してはいけないのに動いてしまう」問題がありました。

![image](https://user-images.githubusercontent.com/3752189/194733966-88c1affe-406f-45f7-96dd-f85205b53010.png)

同じ場所で２回動くのは OK とし、逆に戻す処理を２回動かすよう修正しました → 052961a
（戻す処理を複数回動かしても、マーカーの \a はコマンドラインに普通入ってこないので問題ないはず）

**Comment by hogewest** [comment]
https://github.com/nyaosorg/nyagos/releases/tag/4.4.13_1
上記バージョンで修正されているのを確認しました。
ご対応ありがとうございました！
