### ISSUE TITLE
Update nyagos got script error

### ISSUE THREAD

**Issue by naoyaikeda** [nyaosorg/nyagos#442]
I update nyagos 4.4.14 -> 4.4.15
I got script error.

Nihongo Yet Another GOing Shell 4.4.15_0-windows-amd64 by go1.20.14
(c) 2014-2024 NYAOS.ORG <https://github.com/nyaosorg/nyagos>
C:\Users\gorn\.nyagos:1: attempt to call a non-function object
stack traceback:
        C:\Users\gorn\.nyagos:1: in main chunk
        [G]: ?

.nyagos is as follows.

alias "ll=ls -oFl"

nyagos.alias.printarg = function(args)
    for i=1,#args do
        print(args[i])
    end
end

**Comment by hymkor** [comment]
Would you insert the following lines at the top of `.nyagos` ?

```lua
if not alias then
    require "aliasandset" 
end
```

The script `aliasandset.lua` defines `alias "..."` and it is modified to be not loaded on default at the version 1.20.15 .
I was considering the `alias "..."` is used by few people.
If there were many similar inquiries, I would return to the original specifications in the next version.

**Comment by hymkor** [comment]
On [4.4.15_1](https://github.com/nyaosorg/nyagos/releases/tag/4.4.15_1), `alias "ll=ls -oFl"` is avaliable again .

Would you confirm ?

**Comment by naoyaikeda** [comment]
I confirm problem was solved.

**Comment by hymkor** [comment]
Thank you
